#!/usr/bin/env python

Import("env")

source_files = [
    "display_server_wayland.cpp",
]

objects = []

for source_file in source_files:
    objects.append(env.Object(source_file))

Return("objects")
